### PR TITLE
Main Evontech

### PR DESCRIPTION
**Pull request by adityaevontech**
Added cyberliteracyforall.com website link in top navigation

### CODE REVIEW

**Review by lgorence — CHANGES_REQUESTED** [review]
It should be stylized differently than Cyberliteracyforall. Plus, it's a bit long for a menu item.

@Renukanadkarni any suggestions here?

**Comment by colbycocking** [comment]
The toast location and animation were fine like they were before, please revert them back. The only thing I wanted changed was the css so that it looked like it fit with the rest of the site.

**Comment by adityaevontech** [comment]
> The toast location and animation were fine like they were before, please revert them back. The only thing I wanted changed was the css so that it looked like it fit with the rest of the site.

I have made the changes and reverted. Kindly check and approve the PR request

**Review by adityaevontech — COMMENTED** [review]
Done

**Comment by adityaevontech** [comment]
On Hold for now

**Pull request closed without merging**
