### PR TITLE
Main Evontech

### PR DESCRIPTION
**Pull request by adityaevontech**

### CODE REVIEW

**Review by colbycocking — CHANGES_REQUESTED** [review]
Home looks great, but I would like it to be 5 wide rather than 4 with 1 below. If you can't do that I would rather you just do 4 cards across.

There should be no need to create a separate javascript file for each set of cards. You should be able to use the the challenge-set slug with the list_challenge_set_challenges API  to get the challenges in the challenge set. That way you only ever have to have 1 file no matter how many challenge sets you create. 

If the image is why you are doing it this way, I would suggest just using the same images based on index value for now. In the future I would add an image path to the challenge-set and challenge schemas and then add the respective paths to the json for each challenge and challenge-set.

**Comment by adityaevontech** [comment]
> Home looks great, but I would like it to be 5 wide rather than 4 with 1 below. If you can't do that I would rather you just do 4 cards across.
> 
> There should be no need to create a separate javascript file for each set of cards. You should be able to use the the challenge-set slug with the list_challenge_set_challenges API to get the challenges in the challenge set. That way you only ever have to have 1 file no matter how many challenge sets you create.
> 
> If the image is why you are doing it this way, I would suggest just using the same images based on index value for now. In the future I would add an image path to the challenge-set and challenge schemas and then add the respective paths to the json for each challenge and challenge-set.

I have made the above mentioned changes Kindly review.

**Comment by adityaevontech** [comment]
I had made all the changes requested for.
Home looks great, but I would like it to be 5 wide rather than 4 with 1 below. If you can't do that I would rather you just do 4 cards across. **DONE**

You should be able to use the the challenge-set slug with the list_challenge_set_challenges API to get the challenges in the challenge set. That way you only ever have to have 1 file no matter how many challenge sets you create. **DONE**

**Review by colbycocking — APPROVED** [review]
LGTM

**Pull request merged**
